### ISSUE TITLE
Hey, where is everybody?

### ISSUE THREAD

**Issue by CyberDentist** [USCGA/rift#5]
Friends, please contribute to this wonderful project. 😢
![forever_alone](https://images-na.ssl-images-amazon.com/images/I/41QhYy64F3L.jpg)

**Comment by crypt0clysm** [comment]
Umm maybe

**Comment by DSWIFT01** [comment]
:?

**Comment by crypt0clysm** [comment]
close #5

**Comment by CyberDentist** [comment]
Fixes #5 I guess :(

**Comment by crypt0clysm** [comment]
close
